apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spi-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/spi/spi-operator@sha256:89cfd4f210e5336859f52cd68cc85436a9fd95a8ca398e34b5aa46e57bd077e5
        name: container-image
        resources: {}
status: {}
