apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spi-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/spi/spi-operator@sha256:5d9b01a840b5abc0cabf769e5053fdff3d8e8f7252edd2f63c77a2ae3991e724
        name: container-image
        resources: {}
status: {}
