apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spi-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spi-operator
    app.kubernetes.io/part-of: spi
  name: spi-operator
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: spi-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: spi-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/spi/spi-operator@sha256:69ea8e040bf27089d784d1d97a7850cdc2a38b1b4293689525de7e7bcf2cafa4
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 15m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
