apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spi-oauth
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/spi/spi-oauth@sha256:786c9d42dff55c2a46b703291711b5c25351128993965042bf19213dfc4cb3dd
        name: container-image
        resources: {}
status: {}
