apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spi-oauth
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/spi/spi-oauth@sha256:938e82c37a5e4267794a2c0ad8edf54c6e91dec103d384cced9a8ce010f5c275
        name: container-image
        resources: {}
status: {}
