apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spi-oauth
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spi-oauth
    app.kubernetes.io/part-of: spi
  name: spi-oauthz1ud
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: spi-oauth
    weight: 100
status: {}
